[package]
name = "iron-dbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.17.0"
tokio = { version = "1", features = ["full"] }
snailquote = "0.3.1"
anyhow = "1.0"
static_init = "1.0.2"